name: misspell

on:
  push:
    branches:
      - master
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  misspell:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: misspell
        uses: reviewdog/action-misspell@18ffb61effb93b47e332f185216be7e49592e7e1 # v1
        with:
          locale: "US"
